image: Visual Studio 2015

skip_tags: true
branches:
  only:
    - master

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: iGUJ3bB1+4QiAFE49Z8mNg==
  TRYSTACK_USER1:
    secure: OhISSKZ+IVh/KD9xATCLvRzLT7B0jmen8DyKUZd6kB4=
  TRYSTACK_PWD1:
    secure: SCrPe6XivWUNrAm4Bd/iuPhr1Jt5opGTvrXVqwzzy0o=
  TRYSTACK_USER2:
    secure: jYlrXrfE6ykkIVOCoy3xtVoochPR/2jdWlr4Nw5OmI8=
  TRYSTACK_PWD2:
    secure: LugabkY985CmMFCO/0fZ7rvV0WpF7lNl2Uln8CRu38s=

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt roles\infrastructure\files\ansible_id.enc -secret %APPVEYOR_RDP_PASSWORD%
  - secure-file\tools\secure-file -decrypt roles\infrastructure\files\ansible_id.pub.enc -secret %APPVEYOR_RDP_PASSWORD%

build_script:
  - SET PATH=C:\cygwin64\bin
  - C:\cygwin64\setup-x86_64.exe -q --packages=python2-devel,python2-pip
  - bash -c "pip2 install python-novaclient==5.0.0 ansible==2.1.0.0 shade==1.9.0"
  - sed -i "s/return netifaces.AF_INET6.*/return False/" C:\cygwin64\lib\python2.7\site-packages\shade\_utils.py
  - bash -c "ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''"
  - bash jobs.sh
 
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

